Fix job status type
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: operator does not exist: character varying = jobstatus
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.